host: ninjavan-cash-mgt.apigateway.ninja-capstone.cloud.goog
info: {description: Ninja Van Petty Cash Mgt API gateway, title: ninjavan-cash-mgt,
  version: 3.0.0}
paths:
  /expenseCategories:
    get:
      operationId: getExpenseCategories
      responses:
        '200':
          description: Successfully retrieve list of all expense categories
          schema: {type: string}
      security:
      - api_key: []
      summary: Get list of all expense categories
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
    options:
      operationId: corsExpenseCategories
      responses:
        '200': {description: A successful response}
      summary: Handles pre-flight cors request
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://asia-southeast2-ninja-capstone.cloudfunctions.net/cors'}
    post:
      consumes: [application/x-www-form-urlencoded]
      operationId: postExpenseCategory
      responses:
        '200':
          description: Successfully created an expense category
          schema: {type: string}
      security:
      - api_key: []
      summary: Create a new expense category
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
  /expenseCategories/{expenseCategoryId}:
    delete:
      operationId: deleteExpenseCategory
      parameters:
      - {description: Id of the expense category, in: path, name: expenseCategoryId,
        required: true, type: string}
      responses:
        '200':
          description: Successfully deleted an expense category
          schema: {type: string}
      security:
      - api_key: []
      summary: Delete an expense category
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
    get:
      operationId: getExpenseCategory
      parameters:
      - {description: Id of the expense category, in: path, name: expenseCategoryId,
        required: true, type: string}
      responses:
        '200':
          description: Successfully retrieved the expense category
          schema: {type: string}
      security:
      - api_key: []
      summary: Get an expenseCategory
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
    put:
      consumes: [application/x-www-form-urlencoded]
      operationId: putExpenseCategory
      parameters:
      - {description: Successfully updated an expense category, in: path, name: expenseCategoryId,
        required: true, type: string}
      responses:
        '200':
          description: Successfully updated an expense category
          schema: {type: string}
      security:
      - api_key: []
      summary: Update an expenseCategory
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
  /policies:
    get:
      operationId: getPolicies
      responses:
        '200':
          description: Successfully retrieve list of all policies
          schema: {type: string}
      security:
      - api_key: []
      summary: Get list of all policies
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
    options:
      operationId: corsPolicies
      responses:
        '200': {description: A successful response}
      summary: Handles pre-flight cors request
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://asia-southeast2-ninja-capstone.cloudfunctions.net/cors'}
    post:
      consumes: [application/x-www-form-urlencoded]
      operationId: postPolicy
      responses:
        '200':
          description: Successfully created a policy
          schema: {type: string}
      security:
      - api_key: []
      summary: Create a new policy
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
  /policies/{policyId}:
    delete:
      operationId: deletePolicy
      parameters:
      - {description: Id of the policy, in: path, name: policyId, required: true,
        type: string}
      responses:
        '200':
          description: Successfully deleted a policy
          schema: {type: string}
      security:
      - api_key: []
      summary: Delete a policy
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
    get:
      operationId: getPolicy
      parameters:
      - {description: Id of the policy, in: path, name: policyId, required: true,
        type: string}
      responses:
        '200':
          description: Successfully retrieved the policy
          schema: {type: string}
      security:
      - api_key: []
      summary: Get a policy
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
    put:
      consumes: [application/x-www-form-urlencoded]
      operationId: putPolicy
      parameters:
      - {description: Successfully updated a policy, in: path, name: policyId, required: true,
        type: string}
      responses:
        '200':
          description: Successfully updated a policy
          schema: {type: string}
      security:
      - api_key: []
      summary: Update a policy
      tags: [ninjavan-policy-service]
      x-google-backend: {address: 'https://policy-6l56qfm2ha-as.a.run.app', path_translation: APPEND_PATH_TO_ADDRESS}
produces: [application/json]
schemes: [https]
securityDefinitions:
  api_key: {in: query, name: key, type: apiKey}
swagger: '2.0'
