swagger: '2.0'
info:
  title: ninjavan-cash-mgt
  description: Ninja Van Petty Cash Mgt API gateway
  version: 1.0.0
host: ninjavan-cash-mgt.apigateway.ninja-capstone.cloud.goog
schemes:
- https
produces:
- application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query

paths:
  /transaction:
    get:
      summary: Get list of all transactions
      operationId: getTransactions
      x-google-backend:
        address: https://transaction-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all transactions
          schema:
            type: string

    post:
      summary: Post a transaction form
      operationId: postTransaction
      x-google-backend:
        address: https://transaction-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: amount
          type: string
          required: true
          description: amount reflected in transaction
        - in: formData
          name: username
          type: string
          required: true
          description: owner of transaction.
        - in: formData
          name: currency
          type: string
          required: true
          description: currency of transaction
        - in: formData
          name: expCategory
          type: string
          required: true
          description: expense category of transaction
        - in: formData
          name: claimType
          type: string
          required: true
          description: type of transaction
        - in: formData
          name: officeId
          type: string
          required: true
          description: office id of transaction
        - in: formData
          name: submitterId
          type: string
          required: true
          description: transaction submitter's id
        - in: formData
          name: receiptNumber
          type: string
          required: true
          description: receipt number on the transaction
        - in: formData
          name: vendorNumber
          type: string
          required: true
          description: vendor number on the transaction
        - in: formData
          name: receiptDate
          type: string
          required: true
          description: date on the transaction
        - in: formData
          name: description
          type: string
          description: decription about the transaction
        - in: formData
          name: status
          type: string
          required: true
          description: status of the transaction
        - in: formData
          name: history
          type: string
          required: true
          description: history of the transaction
        - in: formData
          name: claimantName
          type: string
          required: true
          description: name of claimant for the transaction
        - in: formData
          name: vehicleNumber
          type: string
          description: vehicle number of claimant
        - in: formData
          name: receivingOffice
          type: string
          description: office receiving this transaction claim
        - in: formData
          name: cashStatus
          type: string
          required: true
          description: cash status of the transaction
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully created a transaction
          schema:
            type: string

  /transaction/{username}/{id}:
    get:
      summary: Get a transaction by its id
      operationId: getUserTransaction
      x-google-backend:
        address: https://transaction-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - name: username
        in: path
        description: Username who owns this transaction
        required: true
        type: string
      - name: id
        in: path
        required: true
        description: id of the transaction
        type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve a transaction belonging to this user by id
          schema:
            type: string

  /transaction/{username}:
    get:
      summary: Get list of transactions belonging to this user
      operationId: getUserTransactions
      x-google-backend:
        address: https://transaction-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - name: username
        in: path
        description: Username who owns this transaction
        required: true
        type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of transactions belonging to this user
          schema:
            type: string

  /user:
    get:
      summary: Get list of all users
      operationId: getUsers
      x-google-backend:
        address: https://user-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all users
          schema:
            type: string

  /user/{username}:
    get:
      summary: Get a user by username
      operationId: getUserByUsername
      x-google-backend:
        address: https://user-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - name: username
        in: path
        description: Username of the user
        required: true
        type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve the user with this username
          schema:
            type: string

  /office:
    get:
      summary: Get list of all offices
      operationId: getOffices
      x-google-backend:
        address: https://office-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - name: country
        in: query
        description: Filter for country of the office
        type: string
      - name: type
        in: query
        description: Filter for type of the office
        type: string
      - name: businessUnit
        in: query
        description: Filter for business unit of the office
        type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all offices
          schema:
            type: string

  /office/{id}:
    get:
      summary: Get office by id
      operationId: getOfficeById
      x-google-backend:
        address: https://office-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
      - name: id
        in: path
        description: Id of the office
        required: true
        type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve the office with this id
          schema:
            type: string
