swagger: '2.0'
info:
  title: ninjavan-cash-mgt
  description: Ninja Van Petty Cash Mgt API gateway
  version: 1.0.0
host: ninjavan-cash-mgt.apigateway.ninja-capstone.cloud.goog
schemes:
- https
produces:
- application/json
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"

paths:
  /transaction:
    get:
      summary: Get list of all transactions
      operationId: getTransactions
      x-google-backend:
        address: https://transaction-6l56qfm2ha-as.a.run.app/transaction
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all transactions
          schema:
            type: string
  /user:
    get:
      summary: Get list of all users
      operationId: getUsers
      x-google-backend:
        address: https://user-6l56qfm2ha-as.a.run.app/user
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all users
          schema:
            type: string
