swagger: '2.0'
info:
  title: ninjavan-cash-mgt
  description: Ninja Van Petty Cash Mgt API gateway
  version: 1.0.0
host: ninjavan-cash-mgt.apigateway.ninja-capstone.cloud.goog
schemes:
- https
produces:
- application/json

paths:
  /transaction:
    get:
      summary: Get list of all transactions
      operationId: getTransactions
      x-google-backend:
        address: https://transaction-6l56qfm2ha-as.a.run.app/transaction
      responses:
        '200':
          description: Successfully retrieve list of all transactions
          schema:
            type: string
  /user:
    get:
      summary: Get list of all users
      operationId: getUsers
      x-google-backend:
        address: https://user-6l56qfm2ha-as.a.run.app/user
      responses:
        '200':
          description: Successfully retrieve list of all users
          schema:
            type: string

  /:
    get:
      summary: Get home page
      operationId: getHome
      x-google-backend:
        address: https://frontend-6l56qfm2ha-as.a.run.app
      responses:
        '200':
          description: Successfully home page
          schema:
            type: string
