swagger: '2.0'
info:
  title: ninjavan-cash-mgt
  description: Ninja Van Petty Cash Mgt API gateway
  version: 3.0.0
host: ninjavan-cash-mgt.apigateway.ninja-capstone.cloud.goog
schemes:
- https
produces:
- application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query

paths:
  # ninjavan-policy-service starts
  /policies:
    options:
      summary: Handles pre-flight cors request
      operationId: corsPolicies
      x-google-backend:
        address: https://asia-southeast2-ninja-capstone.cloudfunctions.net/cors
      responses:
        '200':
          description: A successful response
      tags:
      - ninjavan-policy-service

    get:
      summary: Get list of all policies
      operationId: getPolicies
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all policies
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    post:
      summary: Create a new policy
      operationId: postPolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/x-www-form-urlencoded
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully created a policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

  /policies/{policyId}:
    get:
      summary: Get a policy
      operationId: getPolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Id of the policy
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieved the policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    delete:
      summary: Delete a policy
      operationId: deletePolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Id of the policy
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully deleted a policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    put:
      summary: Update a policy
      operationId: putPolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Successfully updated a policy
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully updated a policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

  /locations:
    options:
      summary: Handles pre-flight cors request
      operationId: corsLocations
      x-google-backend:
        address: https://asia-southeast2-ninja-capstone.cloudfunctions.net/cors
      responses:
        '200':
          description: A successful response
      tags:
      - ninjavan-policy-service

    get:
      summary: Get list of all locations
      operationId: getLocations
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of all locations
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    post:
      summary: Create a new location
      operationId: postLocation
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/x-www-form-urlencoded
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully created a location
          schema:
            type: string
      tags:
      - ninjavan-policy-service

  /locations/{locationId}:
    get:
      summary: Get a location
      operationId: getLocation
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: locationId
          type: string
          required: true
          description: Id of the location
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieved the location
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    delete:
      summary: Delete a location
      operationId: deleteLocation
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: locationId
          type: string
          required: true
          description: Id of the location
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully deleted a location
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    put:
      summary: Update a location
      operationId: putLocation
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Successfully updated a location
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully updated a location
          schema:
            type: string
      tags:
      - ninjavan-policy-service

  /expenseCategories:
    options:
      summary: Handles pre-flight cors request
      operationId: corsexpenseCategories
      x-google-backend:
        address: https://asia-southeast2-ninja-capstone.cloudfunctions.net/cors
      responses:
        '200':
          description: A successful response
      tags:
      - ninjavan-policy-service

    get:
      summary: Get list of allexpenseCategories
      operationId: getexpenseCategories
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieve list of allexpenseCategories
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    post:
      summary: Create a new policy
      operationId: postPolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/x-www-form-urlencoded
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully created a policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

  /expenseCategories/{policyId}:
    get:
      summary: Get a policy
      operationId: getPolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Id of the policy
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully retrieved the policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    delete:
      summary: Delete a policy
      operationId: deletePolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Id of the policy
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully deleted a policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

    put:
      summary: Update a policy
      operationId: putPolicy
      x-google-backend:
        address: https://policy-6l56qfm2ha-as.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: path
          name: policyId
          type: string
          required: true
          description: Successfully updated a policy
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully updated a policy
          schema:
            type: string
      tags:
      - ninjavan-policy-service

  # ninjavan-policy-service ends
